# Generated by Django 2.2.28 on 2026-02-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20260212_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picute',
            new_name='picture',
        ),
    ]
